export const ACTION_TYPES = {
  GET_SLIDER_CONTENT: Symbol("GET_SLIDER_CONTENT"),
  SET_SLIDER_CONTENT: Symbol("SET_SLIDER_CONTENT"),
  SET_SLIDER_CONTENT_STATE: Symbol("SET_SLIDER_CONTENT_STATE"),
};
